// <auto-generated />
using System;
using Erp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erp.Api.Migrations
{
    [DbContext(typeof(ErpDbContext))]
    [Migration("20260115201604_AddInventoryPartTable")]
    partial class AddInventoryPartTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            

            modelBuilder.Entity("Erp.Api.Models.InventoryPart", b =>
                {
                    b.Property<string>("Contract")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract");

                    b.Property<string>("PartNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_no");

                    b.Property<string>("AccountingGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accounting_group");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("country_of_origin");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("Description")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("description");

                    b.Property<decimal?>("EstimatedMaterialCost")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("estimated_material_cost");

                    b.Property<decimal?>("ExpectedLeadtime")
                        .HasColumnType("numeric(22,0)")
                        .HasColumnName("expected_leadtime");

                    b.Property<decimal?>("ListPrice")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("list_price");

                    b.Property<decimal?>("ListPriceInclTax")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("list_price_incl_tax");

                    b.Property<decimal?>("MaxStorageHumidity")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("max_storage_humidity");

                    b.Property<decimal?>("MaxStorageTemperature")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("max_storage_temperature");

                    b.Property<decimal?>("MinStorageHumidity")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("min_storage_humidity");

                    b.Property<decimal?>("MinStorageTemperature")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("min_storage_temperature");

                    b.Property<string>("PartProductCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("part_product_code");

                    b.Property<string>("PartProductFamily")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("part_product_family");

                    b.Property<string>("PartStatus")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("part_status");

                    b.Property<string>("PlannerBuyer")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("planner_buyer");

                    b.Property<decimal?>("PriceConvFactor")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("price_conv_factor");

                    b.Property<string>("PrimeCommodity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prime_commodity");

                    b.Property<string>("Rowkey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rowkey");

                    b.Property<decimal>("Rowversion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(22,0)")
                        .HasDefaultValue(1m)
                        .HasColumnName("rowversion");

                    b.Property<string>("SalesType")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("sales_type");

                    b.Property<string>("SalesTypeDb")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sales_type_db");

                    b.Property<string>("SalesUnitMeas")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sales_unit_meas");

                    b.Property<string>("SecondCommodity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("second_commodity");

                    b.Property<decimal?>("StandardPackSize")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("standard_pack_size");

                    b.Property<decimal?>("StandardPutawayQty")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("standard_putaway_qty");

                    b.Property<decimal?>("StorageDepthRequirement")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("storage_depth_requirement");

                    b.Property<decimal?>("StorageHeightRequirement")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("storage_height_requirement");

                    b.Property<decimal?>("StorageVolumeRequirement")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("storage_volume_requirement");

                    b.Property<decimal?>("StorageWeightRequirement")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("storage_weight_requirement");

                    b.Property<decimal?>("StorageWidthRequirement")
                        .HasColumnType("numeric(22,2)")
                        .HasColumnName("storage_width_requirement");

                    b.Property<string>("TaxClassId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tax_class_id");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tax_code");

                    b.Property<string>("UnitMeas")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("unit_meas");

                    b.HasKey("Contract", "PartNo");

                    b.ToTable("inventory_part", (string)null);
                });

           
#pragma warning restore 612, 618
        }
    }
}
